# China 2020

china_2020 = ee.new_activity(code = 'china_2020', name = "China 2020", unit = "unit")

china_2020.new_exchange(input = Solar_PV_cen.key, amount = df['China_Num'][0], unit = "kilowatt hour", type = 'technosphere').save()
china_2020.new_exchange(input = Solar_PV_decen.key, amount = df['China_Num'][1], unit = "kilowatt hour", type = 'technosphere').save()
china_2020.new_exchange(input = CSP.key, amount = df['China_Num'][2], unit = "kilowatt hour", type = 'technosphere').save()
china_2020.new_exchange(input = Wind_onshore.key, amount = df['China_Num'][3], unit = "kilowatt hour", type = 'technosphere').save()
china_2020.new_exchange(input = Wind_offshore.key, amount = df['China_Num'][4], unit = "kilowatt hour", type = 'technosphere').save()
china_2020.new_exchange(input = Wave.key, amount = df['China_Num'][5], unit = "kilowatt hour", type = 'technosphere').save()
china_2020.new_exchange(input = Hydro.key, amount = df['China_Num'][6], unit = "kilowatt hour", type = 'technosphere').save()
china_2020.new_exchange(input = Other_renewables.key, amount = df['China_Num'][7], unit = "kilowatt hour", type = 'technosphere').save()
china_2020.new_exchange(input = Nuclear.key, amount = df['China_Num'][8], unit = "kilowatt hour", type = 'technosphere').save()
china_2020.new_exchange(input = Coal_ST.key, amount = df['China_Num'][9], unit = "kilowatt hour", type = 'technosphere').save()
china_2020.new_exchange(input = Oil_ST.key, amount = df['China_Num'][10], unit = "kilowatt hour", type = 'technosphere').save()
china_2020.new_exchange(input = Natural_gas_OC.key, amount = df['China_Num'][11], unit = "kilowatt hour", type = 'technosphere').save()
china_2020.new_exchange(input = Biomass_ST.key, amount = df['China_Num'][12], unit = "kilowatt hour", type = 'technosphere').save()
china_2020.new_exchange(input = IGCC.key, amount = df['China_Num'][13], unit = "kilowatt hour", type = 'technosphere').save()
china_2020.new_exchange(input = Oil_CC.key, amount = df['China_Num'][14], unit = "kilowatt hour", type = 'technosphere').save()
china_2020.new_exchange(input = Natural_gas_CC.key, amount = df['China_Num'][15], unit = "kilowatt hour", type = 'technosphere').save()
china_2020.new_exchange(input = Biomass_CC.key, amount = df['China_Num'][16], unit = "kilowatt hour", type = 'technosphere').save()
china_2020.new_exchange(input = Coal_CCS.key, amount = df['China_Num'][17], unit = "kilowatt hour", type = 'technosphere').save()
china_2020.new_exchange(input = Oil_CCS.key, amount = df['China_Num'][18], unit = "kilowatt hour", type = 'technosphere').save()
china_2020.new_exchange(input = Natural_gas_CCS.key, amount = df['China_Num'][19], unit = "kilowatt hour", type = 'technosphere').save()
china_2020.new_exchange(input = Biomass_CCS.key, amount = df['China_Num'][20], unit = "kilowatt hour", type = 'technosphere').save()
china_2020.new_exchange(input = Coal_CHP.key, amount = df['China_Num'][21], unit = "kilowatt hour", type = 'technosphere').save()
china_2020.new_exchange(input = Oil_CHP.key, amount = df['China_Num'][22], unit = "kilowatt hour", type = 'technosphere').save()
china_2020.new_exchange(input = Natural_gas_CHP.key, amount = df['China_Num'][23], unit = "kilowatt hour", type = 'technosphere').save()
china_2020.new_exchange(input = Biomass_CHP.key, amount = df['China_Num'][24], unit = "kilowatt hour", type = 'technosphere').save()
china_2020.new_exchange(input = Coal_CHP_CCS.key, amount = df['China_Num'][25], unit = "kilowatt hour", type = 'technosphere').save()
china_2020.new_exchange(input = Oil_CHP_CCS.key, amount = df['China_Num'][26], unit = "kilowatt hour", type = 'technosphere').save()
china_2020.new_exchange(input = Natural_gas_CHP_CCS.key, amount = df['China_Num'][27], unit = "kilowatt hour", type = 'technosphere').save()
china_2020.new_exchange(input = Biomass_CHP_CCS.key, amount = df['China_Num'][28], unit = "kilowatt hour", type = 'technosphere').save()

china_2030 = ee.new_activity(code = 'china_2030', name = "China 2030", unit = "unit")

china_2030.new_exchange(input = Solar_PV_cen.key, amount = df['China_Num'][29], unit = "kilowatt hour", type = 'technosphere').save()
china_2030.new_exchange(input = Solar_PV_decen.key, amount = df['China_Num'][30], unit = "kilowatt hour", type = 'technosphere').save()
china_2030.new_exchange(input = CSP.key, amount = df['China_Num'][31], unit = "kilowatt hour", type = 'technosphere').save()
china_2030.new_exchange(input = Wind_onshore.key, amount = df['China_Num'][32], unit = "kilowatt hour", type = 'technosphere').save()
china_2030.new_exchange(input = Wind_offshore.key, amount = df['China_Num'][33], unit = "kilowatt hour", type = 'technosphere').save()
china_2030.new_exchange(input = Wave.key, amount = df['China_Num'][34], unit = "kilowatt hour", type = 'technosphere').save()
china_2030.new_exchange(input = Hydro.key, amount = df['China_Num'][35], unit = "kilowatt hour", type = 'technosphere').save()
china_2030.new_exchange(input = Other_renewables.key, amount = df['China_Num'][36], unit = "kilowatt hour", type = 'technosphere').save()
china_2030.new_exchange(input = Nuclear.key, amount = df['China_Num'][37], unit = "kilowatt hour", type = 'technosphere').save()
china_2030.new_exchange(input = Coal_ST.key, amount = df['China_Num'][38], unit = "kilowatt hour", type = 'technosphere').save()
china_2030.new_exchange(input = Oil_ST.key, amount = df['China_Num'][39], unit = "kilowatt hour", type = 'technosphere').save()
china_2030.new_exchange(input = Natural_gas_OC.key, amount = df['China_Num'][40], unit = "kilowatt hour", type = 'technosphere').save()
china_2030.new_exchange(input = Biomass_ST.key, amount = df['China_Num'][41], unit = "kilowatt hour", type = 'technosphere').save()
china_2030.new_exchange(input = IGCC.key, amount = df['China_Num'][42], unit = "kilowatt hour", type = 'technosphere').save()
china_2030.new_exchange(input = Oil_CC.key, amount = df['China_Num'][43], unit = "kilowatt hour", type = 'technosphere').save()
china_2030.new_exchange(input = Natural_gas_CC.key, amount = df['China_Num'][44], unit = "kilowatt hour", type = 'technosphere').save()
china_2030.new_exchange(input = Biomass_CC.key, amount = df['China_Num'][45], unit = "kilowatt hour", type = 'technosphere').save()
china_2030.new_exchange(input = Coal_CCS.key, amount = df['China_Num'][46], unit = "kilowatt hour", type = 'technosphere').save()
china_2030.new_exchange(input = Oil_CCS.key, amount = df['China_Num'][47], unit = "kilowatt hour", type = 'technosphere').save()
china_2030.new_exchange(input = Natural_gas_CCS.key, amount = df['China_Num'][48], unit = "kilowatt hour", type = 'technosphere').save()
china_2030.new_exchange(input = Biomass_CCS.key, amount = df['China_Num'][49], unit = "kilowatt hour", type = 'technosphere').save()
china_2030.new_exchange(input = Coal_CHP.key, amount = df['China_Num'][50], unit = "kilowatt hour", type = 'technosphere').save()
china_2030.new_exchange(input = Oil_CHP.key, amount = df['China_Num'][51], unit = "kilowatt hour", type = 'technosphere').save()
china_2030.new_exchange(input = Natural_gas_CHP.key, amount = df['China_Num'][52], unit = "kilowatt hour", type = 'technosphere').save()
china_2030.new_exchange(input = Biomass_CHP.key, amount = df['China_Num'][53], unit = "kilowatt hour", type = 'technosphere').save()
china_2030.new_exchange(input = Coal_CHP_CCS.key, amount = df['China_Num'][54], unit = "kilowatt hour", type = 'technosphere').save()
china_2030.new_exchange(input = Oil_CHP_CCS.key, amount = df['China_Num'][55], unit = "kilowatt hour", type = 'technosphere').save()
china_2030.new_exchange(input = Natural_gas_CHP_CCS.key, amount = df['China_Num'][56], unit = "kilowatt hour", type = 'technosphere').save()
china_2030.new_exchange(input = Biomass_CHP_CCS.key, amount = df['China_Num'][57], unit = "kilowatt hour", type = 'technosphere').save()

china_2040 = ee.new_activity(code = 'china_2040', name = "China 2040", unit = "unit")

china_2040.new_exchange(input = Solar_PV_cen.key, amount = df['China_Num'][58], unit = "kilowatt hour", type = 'technosphere').save()
china_2040.new_exchange(input = Solar_PV_decen.key, amount = df['China_Num'][59], unit = "kilowatt hour", type = 'technosphere').save()
china_2040.new_exchange(input = CSP.key, amount = df['China_Num'][60], unit = "kilowatt hour", type = 'technosphere').save()
china_2040.new_exchange(input = Wind_onshore.key, amount = df['China_Num'][61], unit = "kilowatt hour", type = 'technosphere').save()
china_2040.new_exchange(input = Wind_offshore.key, amount = df['China_Num'][62], unit = "kilowatt hour", type = 'technosphere').save()
china_2040.new_exchange(input = Wave.key, amount = df['China_Num'][63], unit = "kilowatt hour", type = 'technosphere').save()
china_2040.new_exchange(input = Hydro.key, amount = df['China_Num'][64], unit = "kilowatt hour", type = 'technosphere').save()
china_2040.new_exchange(input = Other_renewables.key, amount = df['China_Num'][65], unit = "kilowatt hour", type = 'technosphere').save()
china_2040.new_exchange(input = Nuclear.key, amount = df['China_Num'][66], unit = "kilowatt hour", type = 'technosphere').save()
china_2040.new_exchange(input = Coal_ST.key, amount = df['China_Num'][67], unit = "kilowatt hour", type = 'technosphere').save()
china_2040.new_exchange(input = Oil_ST.key, amount = df['China_Num'][68], unit = "kilowatt hour", type = 'technosphere').save()
china_2040.new_exchange(input = Natural_gas_OC.key, amount = df['China_Num'][69], unit = "kilowatt hour", type = 'technosphere').save()
china_2040.new_exchange(input = Biomass_ST.key, amount = df['China_Num'][70], unit = "kilowatt hour", type = 'technosphere').save()
china_2040.new_exchange(input = IGCC.key, amount = df['China_Num'][71], unit = "kilowatt hour", type = 'technosphere').save()
china_2040.new_exchange(input = Oil_CC.key, amount = df['China_Num'][72], unit = "kilowatt hour", type = 'technosphere').save()
china_2040.new_exchange(input = Natural_gas_CC.key, amount = df['China_Num'][73], unit = "kilowatt hour", type = 'technosphere').save()
china_2040.new_exchange(input = Biomass_CC.key, amount = df['China_Num'][74], unit = "kilowatt hour", type = 'technosphere').save()
china_2040.new_exchange(input = Coal_CCS.key, amount = df['China_Num'][75], unit = "kilowatt hour", type = 'technosphere').save()
china_2040.new_exchange(input = Oil_CCS.key, amount = df['China_Num'][76], unit = "kilowatt hour", type = 'technosphere').save()
china_2040.new_exchange(input = Natural_gas_CCS.key, amount = df['China_Num'][77], unit = "kilowatt hour", type = 'technosphere').save()
china_2040.new_exchange(input = Biomass_CCS.key, amount = df['China_Num'][78], unit = "kilowatt hour", type = 'technosphere').save()
china_2040.new_exchange(input = Coal_CHP.key, amount = df['China_Num'][79], unit = "kilowatt hour", type = 'technosphere').save()
china_2040.new_exchange(input = Oil_CHP.key, amount = df['China_Num'][80], unit = "kilowatt hour", type = 'technosphere').save()
china_2040.new_exchange(input = Natural_gas_CHP.key, amount = df['China_Num'][81], unit = "kilowatt hour", type = 'technosphere').save()
china_2040.new_exchange(input = Biomass_CHP.key, amount = df['China_Num'][82], unit = "kilowatt hour", type = 'technosphere').save()
china_2040.new_exchange(input = Coal_CHP_CCS.key, amount = df['China_Num'][83], unit = "kilowatt hour", type = 'technosphere').save()
china_2040.new_exchange(input = Oil_CHP_CCS.key, amount = df['China_Num'][84], unit = "kilowatt hour", type = 'technosphere').save()
china_2040.new_exchange(input = Natural_gas_CHP_CCS.key, amount = df['China_Num'][85], unit = "kilowatt hour", type = 'technosphere').save()
china_2040.new_exchange(input = Biomass_CHP_CCS.key, amount = df['China_Num'][86], unit = "kilowatt hour", type = 'technosphere').save()

china_2050 = ee.new_activity(code = 'china_2050', name = "China 2050", unit = "unit")

china_2050.new_exchange(input = Solar_PV_cen.key, amount = df['China_Num'][87], unit = "kilowatt hour", type = 'technosphere').save()
china_2050.new_exchange(input = Solar_PV_decen.key, amount = df['China_Num'][88], unit = "kilowatt hour", type = 'technosphere').save()
china_2050.new_exchange(input = CSP.key, amount = df['China_Num'][89], unit = "kilowatt hour", type = 'technosphere').save()
china_2050.new_exchange(input = Wind_onshore.key, amount = df['China_Num'][90], unit = "kilowatt hour", type = 'technosphere').save()
china_2050.new_exchange(input = Wind_offshore.key, amount = df['China_Num'][91], unit = "kilowatt hour", type = 'technosphere').save()
china_2050.new_exchange(input = Wave.key, amount = df['China_Num'][92], unit = "kilowatt hour", type = 'technosphere').save()
china_2050.new_exchange(input = Hydro.key, amount = df['China_Num'][93], unit = "kilowatt hour", type = 'technosphere').save()
china_2050.new_exchange(input = Other_renewables.key, amount = df['China_Num'][94], unit = "kilowatt hour", type = 'technosphere').save()
china_2050.new_exchange(input = Nuclear.key, amount = df['China_Num'][95], unit = "kilowatt hour", type = 'technosphere').save()
china_2050.new_exchange(input = Coal_ST.key, amount = df['China_Num'][96], unit = "kilowatt hour", type = 'technosphere').save()
china_2050.new_exchange(input = Oil_ST.key, amount = df['China_Num'][97], unit = "kilowatt hour", type = 'technosphere').save()
china_2050.new_exchange(input = Natural_gas_OC.key, amount = df['China_Num'][98], unit = "kilowatt hour", type = 'technosphere').save()
china_2050.new_exchange(input = Biomass_ST.key, amount = df['China_Num'][99], unit = "kilowatt hour", type = 'technosphere').save()
china_2050.new_exchange(input = IGCC.key, amount = df['China_Num'][100], unit = "kilowatt hour", type = 'technosphere').save()
china_2050.new_exchange(input = Oil_CC.key, amount = df['China_Num'][101], unit = "kilowatt hour", type = 'technosphere').save()
china_2050.new_exchange(input = Natural_gas_CC.key, amount = df['China_Num'][102], unit = "kilowatt hour", type = 'technosphere').save()
china_2050.new_exchange(input = Biomass_CC.key, amount = df['China_Num'][103], unit = "kilowatt hour", type = 'technosphere').save()
china_2050.new_exchange(input = Coal_CCS.key, amount = df['China_Num'][104], unit = "kilowatt hour", type = 'technosphere').save()
china_2050.new_exchange(input = Oil_CCS.key, amount = df['China_Num'][105], unit = "kilowatt hour", type = 'technosphere').save()
china_2050.new_exchange(input = Natural_gas_CCS.key, amount = df['China_Num'][106], unit = "kilowatt hour", type = 'technosphere').save()
china_2050.new_exchange(input = Biomass_CCS.key, amount = df['China_Num'][107], unit = "kilowatt hour", type = 'technosphere').save()
china_2050.new_exchange(input = Coal_CHP.key, amount = df['China_Num'][108], unit = "kilowatt hour", type = 'technosphere').save()
china_2050.new_exchange(input = Oil_CHP.key, amount = df['China_Num'][109], unit = "kilowatt hour", type = 'technosphere').save()
china_2050.new_exchange(input = Natural_gas_CHP.key, amount = df['China_Num'][110], unit = "kilowatt hour", type = 'technosphere').save()
china_2050.new_exchange(input = Biomass_CHP.key, amount = df['China_Num'][111], unit = "kilowatt hour", type = 'technosphere').save()
china_2050.new_exchange(input = Coal_CHP_CCS.key, amount = df['China_Num'][112], unit = "kilowatt hour", type = 'technosphere').save()
china_2050.new_exchange(input = Oil_CHP_CCS.key, amount = df['China_Num'][113], unit = "kilowatt hour", type = 'technosphere').save()
china_2050.new_exchange(input = Natural_gas_CHP_CCS.key, amount = df['China_Num'][114], unit = "kilowatt hour", type = 'technosphere').save()
china_2050.new_exchange(input = Biomass_CHP_CCS.key, amount = df['China_Num'][115], unit = "kilowatt hour", type = 'technosphere').save()



